import json
from pathlib import Path
import pytest

def test_triage_matrix_integrity():
    """Verifies that all possible UI outputs from root configs map to real threat nodes."""
    # 1. Locate config files relative to project layout
    project_root = Path(__file__).resolve().parent.parent
    config_path = project_root / "src" / "config" / "triage_workflow.json"
    
    assert config_path.exists(), f"[-] Missing triage_workflow.json configuration at: {config_path}"
    
    with open(config_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    assert "root_nodes" in data, "[-] JSON missing primary 'root_nodes' baseline."
    assert "threat_nodes" in data, "[-] JSON missing tactical 'threat_nodes' mapping matrix."
    
    # 2. Mirror the UI's hardened translation map boundary
    threat_key_map = {
        "windows": "windows_core_ransomware",
        "linux": "linux_host_ransomware",
        "esxi": "esxi_hypervisor_ransomware",
        "cloud: identity provider": "cloud_idp_compromise",
        "cloud: saas": "cloud_idp_compromise",
        "cloud: office suite": "cloud_idp_compromise",
        "cloud: iaas": "cloud_idp_compromise",
        "cloud: generic": "cloud_idp_compromise"
    }
    
    # 3. Collect all viable option values generated by the root layout tree
    viable_ui_values = set()
    for node_id, node in data["root_nodes"].items():
        for option in node.get("options", []):
            viable_ui_values.add(option["value"].lower().strip())
            
    # 4. Assert that every item mapped in threat_key_map points to an existing JSON database key
    for ui_value, target_node in threat_key_map.items():
        assert target_node in data["threat_nodes"], (
            f"[-] Critical Mapping Defect: UI token mapping '{ui_value}' points to "
            f"a missing threat_node configuration index: '{target_node}'"
        )
        
    # 5. Assert that every tactical question contains valid MITRE ATT&CK identifier syntax
    for matrix_key, question_array in data["threat_nodes"].items():
        for question in question_array:
            tech_id = question.get("technique_id", "")
            assert tech_id.startswith("T1"), (
                f"[-] Structural Error in node {question.get('id', 'UNKNOWN')} "
                f"under matrix '{matrix_key}': Invalid MITRE ATT&CK technique token signature '{tech_id}'"
            )
